### ISSUE TITLE
Algorithm update

### ISSUE THREAD

**Issue by 4kimov** [sqids/sqids-scala#5]
Spec has been updated to simplify the algorithm (along with a few improvements): https://github.com/sqids/sqids-spec/issues/11#issuecomment-1712251403

As of right now, IDs don't match with this repo. @jesperoman Could you please update?

**Comment by jesperoman** [comment]
Finally I think I have a complete PR #7 
I hope I implemented all new tests as well, but some brief sanity check would probably not hurt!

**Comment by 4kimov** [comment]
Hi @jesperoman, thank you for the updates! A few notes:

- The shuffle test is [internal to the spec](https://github.com/sqids/sqids-spec/tree/main/tests/internal) and not really needed: https://github.com/sqids/sqids-scala/blob/simplify-algorithm/src/test/scala/sqids/AlphabetSuite_shuffle.scala (also the bars test within should fail, because those are multibyte characters)
- Allowed range for minLength is now 0-255 (not zero to alphabet length), is this one checking for length 256? https://github.com/sqids/sqids-scala/blob/simplify-algorithm/src/test/scala/sqids/SqidsSuite_minLength.scala#L67 Here's a reference: https://github.com/sqids/sqids-spec/blob/main/tests/minlength.test.ts#L110
- I also couldn't find this one: https://github.com/sqids/sqids-spec/blob/main/tests/minlength.test.ts#L16

Other than that looks good 👍 🙏

**Comment by jesperoman** [comment]
Hopefully, now everything is fixed!
I guess the sanity check was a good thing 😅

**Comment by 4kimov** [comment]
Heh, yep. Cool, thanks for the quick updates!

The only other thing I noticed is the CHANGELOG is empty (feel free to remove it if it's not a part of the Scala ecosystem), but other than that - if the tests are passing - everything looks good to me 💪

**Comment by jesperoman** [comment]
Cool!
Yeah, removed CHANGELOG, it's rarely used in github scala projects, since we have the github releases which should give a pretty clear picture
